- hosts: all
  remote_user: nick
  become: yes

  tasks:
  
  - name: install nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: install Apache
    apt:
      name: apache2
      state: present
      update_cache: yes

  - name: stop service Apache2
    ansible.builtin.service:
      name: apache2
      state: stopped

  - name: Copy index file
    ansible.builtin.copy:
      src: ./files/index.html
      dest: /var/www/html/index.html
      force: true
  
  - name: Copy nginx conf file
    ansible.builtin.copy:
      src: ./files/httpd.conf
      dest: /etc/nginx/conf.d/httpd.conf
     
  - name: Start service apache2
    ansible.builtin.service:
      name: apache2
      state: started